core:
  ignoreSystemCheck: false # ignore system
  arch: arm64 # amd64 arm64
  registry: registry.cn-hangzhou.aliyuncs.com/kube-king # image registry address
  networkAdapter: eth0 # network interface name
containerRuntime:
  type: containerd # container runtime type (containerd , docker)
  version: v1.6.21 # container runtime version
  insecureRegistryList: # container runtime insecure registry list
    - registry.cn-hangzhou.aliyuncs.com
etcd:
  version: v3.5.0 # etcd version
  rootPath: /var/lib/etcd # etcd root path
  replicas: 3 # default replicas is master node number , value must in （1，3，5，7）
kubernetes:
  version: v1.21.5 # kubernetes version
  serviceCidr: 10.91.0.0/16  # service cidr address
  podCidr: 10.241.0.0/16 # pod cidr address
kubeVip:
  enable: true # enable kube-vip
  vip: 10.211.55.200 # vip address
  version: v0.3.8 # kube vip version
cni:
  enable: true # enable cni
  type: calico # cni type (calico)
  version: v3.20.0 # cni version